config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :admin_users
  resources :posts
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable
end

app/models/application_record.rb
# frozen_string_literal: true

# applicationRecord
#
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :admin_user
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application conytroller
class ApplicationController < ActionController::Base
  before_action :current_user
  include Pundit::Authorization
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to root_path
  end

  def current_user
    current_admin_user
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Home controller
#
class HomeController < ApplicationController
  def index; end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# Post Controller
#
class PostsController < ApplicationController
  before_action :find_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    # authorize @post
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    authorize @post
  end

  def edit
    authorize @post
  end

  def update 
    authorize @post
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    authorize @post
    @post.destroy
    redirect_to root_path
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :admin_user_id)
  end
end

app/controllers/registration_controller.rb
# frozen_string_literal: true

# Registration Controller
#
class RegistrationController < ApplicationController
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:First_name, :last_name, :email, :password) }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# applicationhelper
#
module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# Home helper
#
module HomeHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

# Post helper
#
module PostsHelper
end

app/helpers/registration_controller_helper.rb
# frozen_string_literal: true

# Registration Controller
#
module RegistrationControllerHelper
end

app/views/home/index.html.erb
<h1>HOME PAGE</h1>
<br>
<% if admin_user_signed_in? %> 
  <%= current_admin_user.email %>
  <br> <br>
  <%= link_to 'Sign out', destroy_admin_user_session_path ,method: :delete%>
<% else %>
  <%= link_to 'Login', new_admin_user_session_path %>
  <br> <br>
  <%= link_to 'SignUp', new_admin_user_registration_path %>
<% end %>
<br> <br>
<%= link_to 'Posts', posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 
    
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
<%= f.label :title %> <br>
<%= f.text_field :title %><br>
<br>
<%= f.label :body %> <br>
<%= f.text_area :body %> <br>
<br>
<%= f.submit %>
 <% end %>

app/views/posts/index.html.erb
<%= link_to "Create Post", new_post_path %>
<% @posts.each do |post| %>
<h2> Post Number: <%= post.id%> </h2>
<p> Title: <%= post.title %></p>
<br>
<%= link_to "Read", post_path(post) %>
<%= link_to "Edit", edit_post_path(post) %>
<%= link_to "Delete" , post_path(post), method: :delete , data: {Confirm:"Are You Sure?"}%>

<hr>
<% end %>

app/views/posts/new.html.erb
<h1>Post Form</h1>
<%= form_for [@admin_user, @post] do |f| %>
<%= f.label :title %> <br>
<%= f.text_field :title %><br>
<br>
<%= f.label :body %> <br>
<%= f.text_area :body %> <br>
<br>
<%= f.submit %>
 <% end %>

app/views/posts/show.html.erb
<h1> <%= @post.title %></h1>
<div>
<%= @post.body %>
</div>